---
# File: host.yml
#
# Description :
# Cacti client host setup
#
# OS: Debian6 Debian7

- name: Install requires
  yum: name={{ item }} update_cache=yes state=present
  with_items:
    - "{{ cacti_client_required_packages }}"

- name: SNMP CONF
  template: src=etc/snmpd.conf.j2  dest={{ snmp_conf_dir }}/snmpd.conf owner=root group=root mode=0644
  notify: restart_snmpd
  tags: snmp

- name: Create scripts dir
  file: path=/usr/local/scripts/ state=directory
  tags: scripts_dir

- name: Copy NFS CLIENT SCRIPT
  copy: src=hosts_scripts/nfs_client.sh dest=/usr/local/scripts/nfs_client.sh owner=root group=root mode=0744
  when: nfs_client is defined
  tags: snmp

- name: Create cacti user
  user: name=cacti comment="Cacti user for poller process"
  tags: user

- name:  Grant User for Mysql monitoring
  shell: mysql -e "GRANT SUPER, PROCESS ON *.* TO '{{ cacti_mysql_mon_user }}'@'{{ archi_subnet }}.%' IDENTIFIED BY '{{ cacti_mysql_mon_pass }}'";
  when:  mysql_server is defined

- name: Nginx Status conf
  template: src=etc/nginx_status.conf.j2  dest={{ nginx_conf_dir }}/status.conf owner=root group=root mode=0644
  when: nginx_server is defined
  notify: reload_nginx
  tags: nginx_server

- name: ssh key for cacti
  authorized_key: user=cacti key="{{ lookup('file', 'id_rsa.pub') }}"
  tags: ssh_key

- name: Ensure Handlers flushed
  meta: flush_handlers
